// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTools(arg1) {
  return window['go']['main']['App']['CheckTools'](arg1);
}

export function ChooseWorkDir() {
  return window['go']['main']['App']['ChooseWorkDir']();
}

export function ClearEndedTasks() {
  return window['go']['main']['App']['ClearEndedTasks']();
}

export function CreateTask(arg1, arg2) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function Doctor(arg1) {
  return window['go']['main']['App']['Doctor'](arg1);
}

export function FillFormData(arg1) {
  return window['go']['main']['App']['FillFormData'](arg1);
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function GetLoginSession() {
  return window['go']['main']['App']['GetLoginSession']();
}

export function GetTaskCommand(arg1) {
  return window['go']['main']['App']['GetTaskCommand'](arg1);
}

export function GetTaskLog(arg1) {
  return window['go']['main']['App']['GetTaskLog'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenWorkDir(arg1) {
  return window['go']['main']['App']['OpenWorkDir'](arg1);
}

export function RetryFailedTasks() {
  return window['go']['main']['App']['RetryFailedTasks']();
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function StartLogin(arg1) {
  return window['go']['main']['App']['StartLogin'](arg1);
}

export function StartNextPending() {
  return window['go']['main']['App']['StartNextPending']();
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopLogin() {
  return window['go']['main']['App']['StopLogin']();
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function VersionInfo() {
  return window['go']['main']['App']['VersionInfo']();
}
