// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckTools(arg1:main.ToolPaths):Promise<Array<main.ToolDiagnostic>>;

export function ChooseWorkDir():Promise<string>;

export function ClearEndedTasks():Promise<number>;

export function CreateTask(arg1:main.TaskInput,arg2:boolean):Promise<main.TaskDTO>;

export function DeleteTask(arg1:number):Promise<void>;

export function Doctor(arg1:main.ToolPaths):Promise<string>;

export function FillFormData(arg1:number):Promise<main.TaskInput>;

export function GetBootstrap():Promise<main.Bootstrap>;

export function GetLoginSession():Promise<main.LoginSessionDTO>;

export function GetTaskCommand(arg1:number):Promise<string>;

export function GetTaskLog(arg1:number):Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenWorkDir(arg1:string):Promise<void>;

export function RetryFailedTasks():Promise<Array<main.TaskDTO>>;

export function RetryTask(arg1:number):Promise<main.TaskDTO>;

export function RevealFile(arg1:string):Promise<void>;

export function SavePreferences(arg1:main.Preferences):Promise<void>;

export function StartLogin(arg1:string):Promise<main.LoginSessionDTO>;

export function StartNextPending():Promise<void>;

export function StartTask(arg1:number):Promise<void>;

export function StopLogin():Promise<void>;

export function StopTask(arg1:number):Promise<void>;

export function VersionInfo():Promise<main.VersionInfo>;
